### ISSUE TITLE
JWT for auth

### ISSUE THREAD

**Issue by creazero** [free-coders-nutshell/social-network-backend#15]
Subj

**Comment by ridouchire** [comment]
WTF is JWT?

**Comment by creazero** [comment]
JSON Web Token.

**Comment by kugimiya** [comment]
Я даже какую-то хуйню набросал с получением токена и его рефрешем: https://gist.github.com/kugimiya/026313c035b3075baf13a3a26a66b1ee

@creazero, думаю не стоит делать это отдельным микросервисом. Ты согласен?

**Comment by creazero** [comment]
Конечно. Я сразу спросил тебя про нужность отдельного auth-сервиса. Я хочу, чтобы после логина мне прилетал обратно json с:
- token
- expiresIn
- username

**Comment by kugimiya** [comment]
JWT не будет, т.к. это оверхед для сессий. Поправил текущую кодобазу в `f_15`, теперь сессии в базе.
