### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by creazero** [free-coders-nutshell/social-network-backend#21]
Кмк, оно на беке не надо. Ибо все о сессии (токен) хранится у меня. Тебе только возвращать этот токен надо при логине и чекать его валидность при запросах.

**Comment by kugimiya** [comment]
Так или иначе JWT предусматривает механизм отзыва токенов.

**Comment by creazero** [comment]
Но ведь logout это просто `localStorage.del('token')`. На беке у тебя отзыв не вовремя логаута, а во время проверки на `expired`.

**Comment by kugimiya** [comment]
@creazero Иными словами эти сессии будут просто висеть где-то в памяти, пока не запустится проверочка?
