### ISSUE TITLE
Use mocking instead of real database

### ISSUE THREAD

**Issue by creazero** [free-coders-nutshell/social-network-backend#4]
We should start using one of [libraries](https://github.com/mochajs/mocha/wiki#mocks-stubs--spies) instead of a real MySQL.

**Comment by kugimiya** [comment]
Не очень понимаю, что это и зачем. Обесни, плз, с примером, как заюзать в кейсе добавления записи в БД.

**Comment by kugimiya** [comment]
@creazero ну але
